### ISSUE TITLE
Stage 3 Criteria

### ISSUE THREAD

**Issue by peetklecha** [tc39/proposal-promise-with-resolvers#13]
- [x] complete spec text
- [x] reviewers
  - [x] @ljharb 
  - [x] @jridgewell 
- [x] editors
  - [x] @syg
  - [x] @bakkot
  - [x] @michaelficarra

**Comment by bakkot** [comment]
LGTM

**Comment by ljharb** [comment]
spec text LGTM.

(not as a reviewer, but for your info, the issues on the slides: `promise.resolve()` imo is a nonstarter, and i'd love to bikeshed the name further, but otherwise i think the semantics are the only thing they can be)

**Comment by jridgewell** [comment]
LGTM

**Comment by michaelficarra** [comment]
LGTM modulo #14 and a resolution on #2.

**Comment by peetklecha** [comment]
This proposal has reached Stage 3.
