### ISSUE TITLE
deploy the spec?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-promise-with-resolvers#8]
The current github pages site is just the readme. It'd be great if that could be the rendered spec (the ecmarkup output)

**Comment by jridgewell** [comment]
The template build action combined with setting up GH Pages works well for auto-deploying: https://github.com/tc39/template-for-proposals/blob/main/.github/workflows/build.yml

**Comment by peetklecha** [comment]
i thought the repo was configured to deploy, but the deploy failed with this error:

```
remote: Permission to tc39/proposal-promise-with-resolvers.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/tc39/proposal-promise-with-resolvers.git/': The requested URL returned error: 403
```

does the github-actions bot need explicit perms? if so @ljharb are you able to add?

**Comment by ljharb** [comment]
The repo is currently configured to deploy from the main branch, so all you'd need is an index.html. There's no no gh-pages branch at all right now.

**Comment by ljharb** [comment]
That said, there was also a permissions issue which I think I've just fixed.

**Comment by ljharb** [comment]
Looks like the spec is deployed now https://tc39.es/proposal-promise-with-resolvers/
